# Generated by Django 2.2.12 on 2021-09-19 09:03

import apps.autodrive.customize_fields
import apps.autodrive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('session_key', models.CharField(blank=True, default='', max_length=40, verbose_name='会话ID')),
                ('token', models.CharField(blank=True, max_length=50, null=True, verbose_name='临时令牌')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='用户组名称')),
                ('supergroup', models.BooleanField(default=False, verbose_name='超级用户组')),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('car', 'car')], default='car', editable=False, max_length=10, verbose_name='用户类型')),
                ('longitude', models.FloatField(default=0.0, verbose_name='经度')),
                ('latitude', models.FloatField(default=0.0, verbose_name='纬度')),
                ('soc', models.IntegerField(default=-1, verbose_name='剩余电量')),
                ('system_state', models.CharField(default='unknown', max_length=30, verbose_name='系统状态')),
            ],
            bases=('autodrive.user',),
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('web', 'web')], default='web', editable=False, max_length=10, verbose_name='用户类型')),
                ('is_super', models.BooleanField(default=False, verbose_name='是否超级用户')),
            ],
            bases=('autodrive.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=apps.autodrive.models.default_user_group, on_delete=django.db.models.deletion.PROTECT, to='autodrive.UserGroup'),
        ),
        migrations.CreateModel(
            name='NavPathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('points_file', apps.autodrive.customize_fields.RestrictedFileField(null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径点文件')),
                ('extend_file', apps.autodrive.customize_fields.RestrictedFileField(blank=True, null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径拓展文件')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='路径名称')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autodrive.WebUser', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '导航路径',
                'verbose_name_plural': '导航路径',
            },
        ),
    ]
