# Generated by Django 2.2.12 on 2021-07-28 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('car', 'car')], default='car', editable=False, max_length=10, verbose_name='用户类型')),
            ],
            bases=('autodrive.user',),
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('client', 'operator')], default='client', editable=False, max_length=10, verbose_name='用户类型')),
            ],
            bases=('autodrive.user',),
        ),
    ]
