# Generated by Django 2.2.12 on 2021-08-09 22:35

import apps.autodrive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户ID')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='用户名称')),
                ('password', models.CharField(max_length=20, verbose_name='用户密码')),
                ('token', models.CharField(blank=True, max_length=50, null=True, verbose_name='临时令牌')),
                ('is_online', models.BooleanField(default=False, verbose_name='是否在线')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否活跃')),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='用户组名称')),
                ('supergroup', models.BooleanField(default=False, verbose_name='超级用户组')),
            ],
        ),
        migrations.CreateModel(
            name='CarUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('car', 'car')], default='car', editable=False, max_length=10, verbose_name='用户类型')),
            ],
            bases=('autodrive.user',),
        ),
        migrations.CreateModel(
            name='WebUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autodrive.User')),
                ('type', models.CharField(choices=[('web', 'web')], default='web', editable=False, max_length=10, verbose_name='用户类型')),
                ('is_super', models.BooleanField(default=False, verbose_name='是否超级用户')),
            ],
            bases=('autodrive.user',),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=apps.autodrive.models.default_user_group, on_delete=django.db.models.deletion.PROTECT, to='autodrive.UserGroup'),
        ),
    ]
