# Generated by Django 2.2.12 on 2021-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='临时令牌'),
        ),
    ]
