# Generated by Django 2.2.12 on 2021-08-10 14:33

import apps.autodrive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavPathInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('points_file', models.FileField(null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径点文件')),
                ('extend_file', models.FileField(blank=True, null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径拓展文件')),
                ('path_name', models.CharField(max_length=30, null=True, verbose_name='路径名称')),
                ('uploader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autodrive.WebUser', verbose_name='上传者')),
            ],
        ),
    ]
