# Generated by Django 2.2.12 on 2021-07-30 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(max_length=50, null=True, verbose_name='临时令牌'),
        ),
    ]
