# Generated by Django 2.2.12 on 2021-08-10 15:42

import apps.autodrive.customize_fields
import apps.autodrive.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0002_navpathinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navpathinfo',
            name='extend_file',
            field=apps.autodrive.customize_fields.RestrictedFileField(blank=True, null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径拓展文件'),
        ),
        migrations.AlterField(
            model_name='navpathinfo',
            name='points_file',
            field=apps.autodrive.customize_fields.RestrictedFileField(null=True, upload_to=apps.autodrive.models.NavPathInfo.file_path, verbose_name='路径点文件'),
        ),
    ]
