# Generated by Django 2.2.12 on 2021-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0002_auto_20210919_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='op_lock',
            field=models.BooleanField(default=False, verbose_name='操作锁'),
        ),
    ]
