# Generated by Django 2.2.12 on 2021-08-05 13:52

import apps.autodrive.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0002_auto_20210805_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(default=apps.autodrive.models.default_user_group, on_delete=django.db.models.deletion.PROTECT, to='autodrive.UserGroup'),
        ),
    ]
