# Generated by Django 2.2.12 on 2021-07-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='是否在线'),
        ),
    ]
