# Generated by Django 2.2.12 on 2021-09-25 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0003_user_op_lock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caruser',
            options={'verbose_name': '车端用户', 'verbose_name_plural': '车端用户'},
        ),
        migrations.AlterModelOptions(
            name='usergroup',
            options={'verbose_name': '用户组', 'verbose_name_plural': '用户组'},
        ),
        migrations.AlterModelOptions(
            name='webuser',
            options={'verbose_name': '远程端用户', 'verbose_name_plural': '远程端用户'},
        ),
        migrations.AlterField(
            model_name='navpathinfo',
            name='name',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True, verbose_name='路径名称'),
        ),
    ]
