# Generated by Django 2.2.12 on 2021-08-10 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0003_auto_20210810_2342'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navpathinfo',
            options={'verbose_name': '导航路径', 'verbose_name_plural': '导航路径'},
        ),
    ]
