# Generated by Django 2.2.12 on 2021-08-05 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0003_auto_20210805_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='supergroup',
            field=models.BooleanField(default=False, verbose_name='超级用户组'),
        ),
    ]
