# Generated by Django 2.2.12 on 2021-09-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0004_auto_20210925_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='登录时间'),
        ),
        migrations.AlterField(
            model_name='navpathinfo',
            name='name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='路径名称'),
        ),
    ]
