# Generated by Django 2.2.12 on 2021-08-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0004_usergroup_supergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='webuser',
            name='is_super',
            field=models.BooleanField(default=False, verbose_name='是否超级用户'),
        ),
    ]
