# Generated by Django 2.2.12 on 2021-08-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0004_auto_20210811_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navpathinfo',
            name='path_name',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='路径名称'),
        ),
    ]
