# Generated by Django 2.2.12 on 2021-08-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0005_webuser_is_super'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webuser',
            name='type',
            field=models.CharField(choices=[('web', 'web')], default='web', editable=False, max_length=10, verbose_name='用户类型'),
        ),
    ]
