# Generated by Django 2.2.12 on 2021-08-10 18:05

import apps.autodrive.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0005_auto_20210811_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='navpathinfo',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='是否活跃'),
        ),
    ]
