# Generated by Django 2.2.12 on 2021-08-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0006_auto_20210811_0205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navpathinfo',
            old_name='path_name',
            new_name='name',
        ),
    ]
