# Generated by Django 2.2.12 on 2021-08-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0007_auto_20210811_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_key',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='会话ID'),
        ),
    ]
