# Generated by Django 2.2.12 on 2021-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0008_user_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='caruser',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10, verbose_name='经度'),
        ),
        migrations.AddField(
            model_name='caruser',
            name='soc',
            field=models.IntegerField(default=-1, verbose_name='剩余电量'),
        ),
    ]
