# Generated by Django 2.2.12 on 2021-08-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autodrive', '0010_auto_20210825_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='caruser',
            name='system_state',
            field=models.CharField(default='unknown', max_length=30, verbose_name='系统状态'),
        ),
    ]
