# Generated by Django 2.2.12 on 2021-08-09 22:35

import apps.helloworld.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FileField(null=True, upload_to=apps.helloworld.models.get_file_path, verbose_name='用户头像')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='图片名称')),
            ],
        ),
    ]
