# Generated by Django 2.2.12 on 2021-08-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helloworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.CharField(max_length=20, null=True, verbose_name='用户名'),
        ),
    ]
